version: '2'
services:
  react_jhipster_learn-app:
    image: react_jhipster_learn
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://react_jhipster_learn-postgresql:5432/react_jhipster_learn
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://react_jhipster_learn-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://react_jhipster_learn-elasticsearch:9200
    ports:
      - 8080:8080
  react_jhipster_learn-postgresql:
    extends:
      file: postgresql.yml
      service: react_jhipster_learn-postgresql
  react_jhipster_learn-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: react_jhipster_learn-elasticsearch
